/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include "stm32f446xx_gpio_driver.h"
//#include "stm32f446xx_lcd_driver.h"

void delay(int time) {
    for(int i = 0 ; i < time ; i++);
}

int main(void){

    gpio_handle_t  led;

	led.pgpiox = GPIOA;
	led.gpio_pinconfig.pin_mode = GPIO_PIN_MODE_OUT;
	led.gpio_pinconfig.pin_number = GPIO_PIN_5;//5
	led.gpio_pinconfig.pin_speed = GPIO_PIN_SPEED_MED;
	led.gpio_pinconfig.pin_optype =  GPIO_OP_PUSH_PULL;
	led.gpio_pinconfig.pin_pupd_ctrl = GPIO_PIN_NO_PUPD;
	gpio_init(&led);

	while(1){
		for (int i = 0 ; i < 4 ; i++){
			gpio_toggle_pin(GPIOA, 5);
			delay(5000000);
		}
		delay(500000);
	}
	return 0;
}
